export const GET_POST = 'GET_POST';
export const FETCH_POSTS = 'FETCH_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'